// lib/models/task.dart
import 'package:hive/hive.dart';

part 'task.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0) // Unique ID for this type within Hive
enum RecurrenceFrequency {
  @HiveField(0)
  none,
  @HiveField(1)
  daily,
  @HiveField(2)
  weekly,
  @HiveField(3)
  monthly,
}

@HiveType(typeId: 1) // Unique ID for Task type
class Task extends HiveObject {
  // Extend HiveObject for easier persistence
  @HiveField(0)
  String id; // Unique ID for each task
  @HiveField(1)
  String title;
  @HiveField(2)
  String description;
  @HiveField(3)
  int currentCount;
  @HiveField(4)
  int targetCount;
  @HiveField(5)
  RecurrenceFrequency recurrenceFrequency;
  @HiveField(6)
  DateTime? expiryDate; // Nullable for tasks without expiry

  Task({
    required this.id,
    required this.title,
    this.description = '',
    this.currentCount = 0,
    this.targetCount = 1,
    this.recurrenceFrequency = RecurrenceFrequency.none,
    this.expiryDate,
  });

  // Helper to check if task is complete
  bool get isComplete => currentCount >= targetCount;

  // Method to reset count based on recurrence (simplified for this example)
  void resetCount() {
    currentCount = 0;
  }
}
